version: "3.8"

services:
  # techdemo-api:
  #   container_name: techdemo-api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5001:5001"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   restart: on-failure
  #   networks:
  #     - app-network

  sqlserver-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "devP@ss123"
    ports:
      - "1433:1433"
    networks:
      - app-network
    restart: always
    volumes:
      - sql-server-data:/var/opt/mssql/

  # elasticsearch:
  #   container_name: elasticsearch
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
  #   ports:
  #     - 9200:9200
  #   volumes:
  #     - elasticsearch-data:/usr/share/elasticseaach/data
  #   environment:
  #     - xpack.security.enabled=false
  #     - discovery.type=sigle-node
  #   networks:
  #     - app-network
  #
  # kibana:
  #   container_name: kibana
  #   image: docker.elastic.co/kibana/kibana:8.7.1
  #   ports:
  #     - 5601:5601
  #   environment:
  #     - ELASTICSEACH_URL=http://localhost:9200
  #   networks:
  #     - app-network
  #   depends_on:
  #     - elasticsearch

volumes:
  elasticseach-data:
  sql-server-data:

networks:
  app-network:
    driver: bridge
